stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.10
  services:
    - postgres:13
  script:
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
